Audit/urls.py
from django.urls import path
from . import views 

app_name = 'Audit'
urlpatterns = [

    # urls for everyone 
    path('Groups/', views.GroupsView.as_view(), name='audit_groups'),
    path('UserComments/',views.CommentView.as_view(), name='audit_comments'),
    path('GroupComparisons/',views.GroupComparisons.as_view(), name='audit_comparisons'),

    # urls for auditors
    path('AuditTripleList/', views.audit_triples, name='audit_triple_list'),
    path('AuditTripleCards/', views.audit_triple_cards, name='audit_triple_cards'),
    #path('AuditType/create/', AuditTypeCreate.as_view(), name='audit_type_create'),
    path('AuditTriple/<uuid:pk>/Update/', views.AuditTripleUpdate.as_view(), name='audit_triple_update'),

    # urls for admins
    path('UserTripleViewList/',views.UserTripleViewList.as_view(), name='audit_user_triple_list'),
    path('UserTripleViewCards/', views.UserTripleView.as_view(), name='audit_user_triple_cards'),
    path('<pk>/', views.AuditTripleDetailView.as_view(), name='audit_triple_detail'),

    path('delete/dataset/<pk>/', views.DeleteDataset.as_view(), name='audit_delete_dataset'),
    path('list/dataset/', views.ListDatasets.as_view(), name='audit_list_datasets'),

]

Charts/urls.py
from django.urls import path
from . import views

app_name = 'Charts'
urlpatterns = [
    path('degree/Verified', views.display_verified_degree_view, name='degree_verified'),
    path('relation/Verified', views.display_verified_relation_view, name='relation_verified'),
    path('out-relations/Verified', views.display_verified_out_relations_view, name='out_relations_verified'),

    path('degree/UnVerified', views.display_unverified_degree_view, name='degree_unverified'),
    path('relation/UnVerified', views.display_unverified_relation_view, name='relation_unverified'),
    path('out-relations/UnVerified', views.display_unverified_out_relations_view, name='out_relations_unverified'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

    # third party
    path('accounts/login/', include('allauth.urls')),

    # local
    path('', include('pages.urls')),
    path('UploadData/', include('UploadData.urls')),
    path('DisplayGraph/', include('DisplayGraph.urls')),
    path('Entities/', include('Entities.urls')),
    path('Types/', include('Types.urls')),
    path('Relations/', include('Relations.urls')),
    path('Charts/', include('Charts.urls')),
    path('Audit/', include('Audit.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Charts/views.py
from django.shortcuts import render
from UploadData import helper_methods as h
from collections import Counter
import networkx as nx
# Create your views here.

def charts_verified_view(request):
    context = dict()
    if "GET" == request.method:
        return render(request,'verified_charts.html',context)


def display_verified_relation_view(request):
    context = dict()
    G = h.create_graph(request,'Verified')
    counter = Counter(sorted(nx.get_edge_attributes(G,'relation').values()))
    context['data']=dict(counter)

    if "GET" == request.method:
        return render(request,'verified_relation_chart.html',context)


def display_verified_degree_view(request):

    context = dict()
    G = h.create_graph(request,'Verified')
    data = G.degree
    context['data'] = dict(sorted(data))

    if "GET" == request.method:
        return render(request,'display_verified_charts.html',context)

    else:
        return render(request,'display_verified_charts.html',context)

def display_verified_out_relations_view(request):
    context = dict()
    G = h.create_graph(request,'Verified') 
    node_relations = dict()
    relations = list()
    for node in G.nodes():
        out_edges = G.out_edges(node,data='relation')
        relations = [rel[2] for rel in out_edges]
        node_relations[node] = dict(Counter(relations))

    counter = Counter(node_relations)

    context['nodes'] = sorted({k:counter[k] for k in counter})
    context['data'] = {k:counter[k] for k in counter}

    if "GET" == request.method:
        return render(request,'display_verified_out_relations.html',context)

def charts_unverified_view(request):
    context = dict()
    if "GET" == request.method:
        return render(request,'display_unverifid_charts.html',context)


def display_unverified_relation_view(request):
    context = dict()
    G = h.create_graph(request,'UnVerified')
    counter = Counter(sorted(nx.get_edge_attributes(G,'relation').values()))
    context['data']=dict(counter)

    if "GET" == request.method:
        return render(request,'unverified_relation_chart.html',context)


def display_unverified_degree_view(request):

    context = dict()
    G = h.create_graph(request,'UnVerified')
    data = G.degree
    context['data'] = dict(sorted(data))

    if "GET" == request.method:
        return render(request,'display_unverified_charts.html',context)

    else:
        return render(request,'display_unverified_charts.html',context)

def display_unverified_out_relations_view(request):
    context = dict()
    G = h.create_graph(request,'UnVerified') 
    node_relations = dict()
    relations = list()
    for node in G.nodes():
        out_edges = G.out_edges(node,data='relation')
        relations = [rel[2] for rel in out_edges]
        node_relations[node] = dict(Counter(relations))

    counter = Counter(node_relations)

    context['nodes'] = sorted({k:counter[k] for k in counter})
    context['data'] = {k:counter[k] for k in counter}

    if "GET" == request.method:
        return render(request,'display_unverified_out_relations.html',context)

Charts/templates/display_charts.html
<!-- Charts/display_verified_charts.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'verified_graph_menu.html' %}
<h1 class="text-center py-2">Make you own Charts</h1>
<h3>Number of edges(degree) associated</h3>
{% include 'chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for d in data %}
      <option value="{{d}}">{{d}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/dcharts.js' %}"></script>

{% endblock content %}

Charts/templates/display_out_relations.html
<!-- Charts/display_out_relations.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'graph_menu.html' %}
<h1 class="text-center py-2">Make you own Charts</h1>
<div class="row">
<h3>Number of edges associated with relation</h3>
</div>
{% include 'chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for node in nodes %}
      <option value="{{node}}">{{node}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/out_relations_chart.js' %}"></script>
{% endblock content %}

Charts/templates/display_unverified_charts.html
<!-- Charts/display_unverified_charts.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'unverified_graph_menu.html' %}
<h1 class="text-center py-2">Combined Dataset</h1>
<h1 class="text-center py-2">Make you own Charts</h1>
<h3>Number of edges(degree) associated with entity</h3>
{% include 'unverified_chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for d in data %}
      <option value="{{d}}">{{d}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/dcharts.js' %}"></script>

{% endblock content %}

Charts/templates/display_unverified_out_relations.html
<!-- Charts/display_unverified_out_relations.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'unverified_graph_menu.html' %}
<h1 class="text-center py-2">Combined Dataset</h1>
<h1 class="text-center py-2">Make you own Charts</h1>
<div class="row">
<h3>Number of edges associated with relation</h3>
</div>
{% include 'unverified_chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for node in nodes %}
      <option value="{{node}}">{{node}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/out_relations_chart.js' %}"></script>

{% endblock content %}

Charts/templates/display_verified_charts.html
<!-- Charts/display_verified_charts.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'verified_graph_menu.html' %}
<h1 class="text-center py-2">Offical Dataset</h1>
<h1 class="text-center py-2">Make you own Charts</h1>
<h3>Number of edges(degree) associated with entity</h3>
{% include 'verified_chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for d in data %}
      <option value="{{d}}">{{d}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/dcharts.js' %}"></script>

{% endblock content %}

Charts/templates/display_verified_out_relations.html
<!-- Charts/display_verified_out_relations.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'verified_graph_menu.html' %}
<h1 class="text-center py-2">Official Dataset</h1>
<h1 class="text-center py-2">Make you own Charts</h1>
<div class="row">
<h3>Number of edges associated with relation</h3>
</div>
{% include 'verified_chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for node in nodes %}
      <option value="{{node}}">{{node}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/out_relations_chart.js' %}"></script>

{% endblock content %}

Charts/templates/relation_chart.html
<!-- Charts/relation_chart.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'graph_verified_menu.html' %}
<h1 class="text-center py-2">Make you own Charts</h1>
<div class="row">
<h3>Number of edges associated with relation</h3>
</div>
{% include 'chart_verified_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for d in data %}
      <option value="{{d}}">{{d}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/relation_chart.js' %}"></script>

{% endblock content %}

Charts/templates/unverified_chart_menu.html
<a href="{% url 'Charts:degree_unverified' %}"><button type="button" class="btn btn-secondary">Degree</button></a>
<a href="{% url 'Charts:relation_unverified' %}"><button type="button" class="btn btn-secondary">Relation</button></a>
<a href="{% url 'Charts:out_relations_unverified' %}"><button type="button" class="btn btn-secondary">Out Relations</button></a>

Charts/templates/unverified_relation_chart.html
<!-- Charts/unverified_relation_chart.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'unverified_graph_menu.html' %}
<h1 class="text-center py-2">Combined Dataset</h1>
<h1 class="text-center py-2">Make you own Charts</h1>
<div class="row">
<h3>Number of edges associated with relation</h3>
</div>
{% include 'unverified_chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for d in data %}
      <option value="{{d}}">{{d}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/relation_chart.js' %}"></script>

{% endblock content %}

Charts/templates/verified_chart_menu.html
<a href="{% url 'Charts:degree_verified' %}"><button type="button" class="btn btn-secondary">Degree</button></a>
<a href="{% url 'Charts:relation_verified' %}"><button type="button" class="btn btn-secondary">Relation</button></a>
<a href="{% url 'Charts:out_relations_verified' %}"><button type="button" class="btn btn-secondary">Out Relations</button></a>

Charts/templates/verified_relation_chart.html
<!-- Charts/verified_relation_chart.html -->
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% include 'verified_graph_menu.html' %}
<h1 class="text-center py-2">Official Dataset</h1>
<h1 class="text-center py-2">Make you own Charts</h1>
<div class="row">
<h3>Number of edges associated with relation</h3>
</div>
{% include 'verified_chart_menu.html' %}
  <form class="d-flex py-3">
    <select name="select_box" class="form-select" id="select_box">
      {% for d in data %}
      <option value="{{d}}">{{d}}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-success" id="myBtn" onClick="lick({{data}});" type="button">Search</button>
  </form>
  </div>
</div>  
<div class="container min-vw-100 min-vh-100">  
<canvas id="canv"></canvas>
</div>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script src="{% static 'Charts/relation_chart.js' %}"></script>

{% endblock content %}