Audit/urls.py
from django.urls import path
from . import views 

app_name = 'Audit'
urlpatterns = [

    # urls for everyone 
    path('Groups/', views.GroupsView.as_view(), name='audit_groups'),
    path('UserComments/',views.CommentView.as_view(), name='audit_comments'),
    path('GroupComparisons/',views.GroupComparisons.as_view(), name='audit_comparisons'),

    # urls for auditors
    path('AuditTripleList/', views.audit_triples, name='audit_triple_list'),
    path('AuditTripleCards/', views.audit_triple_cards, name='audit_triple_cards'),
    #path('AuditType/create/', AuditTypeCreate.as_view(), name='audit_type_create'),
    path('AuditTriple/<uuid:pk>/Update/', views.AuditTripleUpdate.as_view(), name='audit_triple_update'),

    # urls for admins
    path('UserTripleViewList/',views.UserTripleViewList.as_view(), name='audit_user_triple_list'),
    path('UserTripleViewCards/', views.UserTripleView.as_view(), name='audit_user_triple_cards'),
    path('<pk>/', views.AuditTripleDetailView.as_view(), name='audit_triple_detail'),

    path('delete/dataset/<pk>/', views.DeleteDataset.as_view(), name='audit_delete_dataset'),
    path('list/dataset/', views.ListDatasets.as_view(), name='audit_list_datasets'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

    # third party
    path('accounts/login/', include('allauth.urls')),

    # local
    path('', include('pages.urls')),
    path('UploadData/', include('UploadData.urls')),
    path('DisplayGraph/', include('DisplayGraph.urls')),
    path('Entities/', include('Entities.urls')),
    path('Types/', include('Types.urls')),
    path('Relations/', include('Relations.urls')),
    path('Charts/', include('Charts.urls')),
    path('Audit/', include('Audit.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Audit/models.py
from django.db import models
import uuid
from django.contrib.auth import get_user_model

# Create your models here.

class Dataset(models.Model):
    name = models.CharField(max_length=255,)

    def __str__(self):
        return self.name 

class Type(models.Model):

    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,default='')
    dataset = models.ForeignKey(Dataset,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name 

    class Meta:
        ordering = ('name',)

class AuditTriple(models.Model):

    id = models.UUIDField(
    
        primary_key=True,
        default=uuid.uuid4,
        editable=False

    ) 

    dataset = models.ForeignKey(Dataset,on_delete=models.CASCADE)

    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,default='')

    entityA = models.CharField(max_length=255)
    entityA_types = models.ManyToManyField(Type,blank=True,related_name="entityA_types")

    relation = models.CharField(max_length=255)

    entityB = models.CharField(max_length=255)
    entityB_types = models.ManyToManyField(Type,blank=True,related_name="entityB_types")

    comment = models.TextField(blank=True,verbose_name="comments",help_text="Enter a optional reason for un verifing")

    verified = models.BooleanField(default=True)

    class Meta:
        ordering = ('relation',)

    def __str__(self):
        return self.entityA + '---->' + self.relation + '---->' + self.entityB 

Audit/forms.py
from django import forms
from .models import Dataset
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, HTML, Submit
from Audit.fields import ListTextWidget

from .models import AuditTriple

class AuditTripleForm(forms.ModelForm):
    class Meta:
        model = AuditTriple
        fields = ('verified',)

class AuditUpdateForm(forms.ModelForm):
    entityA = forms.CharField(disabled=True)
    relation = forms.CharField(disabled=True)
    entityB = forms.CharField(disabled=True)
    class Meta:
        model = AuditTriple
        fields = ('entityA','relation','entityB','comment',)

class AuditFunctionalForm(forms.Form):
    verified_choices = (
        ('Unknown', 'Unknown'),
        ('True', 'True'),
        ('False', 'False'),
    )
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")

        super(AuditFunctionalForm,self).__init__(*args, **kwargs)

        self.relation_qs = AuditTriple.objects.filter(user=self.request.user).values_list('relation').distinct()

        self.fields['relation'] = forms.CharField(required=False)
        self.fields['relation'].widget = ListTextWidget(self.relation_qs, 'relation_list')
        self.fields['relation'].queryset = AuditTriple.objects.filter(user=self.request.user).distinct()
            
        self.fields['entityA'] =  forms.CharField(required=False)
        self.fields['entityB'] =  forms.CharField(required=False)


    helper = FormHelper()
    helper.form_method = 'GET'

    # seems to work without defining these
    # helper.form_action = reverse_lazy('Audit/AuditTriple/List/')
    # helper.form_action = 'index'

    # submit
    helper.add_input(Submit('submit', 'Submit'))

    # fields
    # user = ForeignKey(get_user_model(),on_delete=models.CASCADE,default='')

    dataset = forms.ModelChoiceField(required=False, queryset=Dataset.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    #relation_qs = AuditTriple.objects.values_list('relation').distinct()
    #relation = forms.CharField(required=False, widget=ListTextWidget(relation_qs, 'relation_list'))
    #relation = forms.CharField(required=False )
    #entityA = forms.CharField(required=False)
    #entityB = forms.CharField(required=False)
    verified = forms.ChoiceField(choices=verified_choices, widget=forms.Select(attrs={'class': 'form-control'}))

Audit/views.py
from django.views.generic.list import ListView
from django.urls import reverse
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
from .models import AuditTriple, Dataset
from django.contrib.auth.models import Group
from django.core.paginator import Paginator
from .filters import  AuditTripleFilter, AuditUserTripleFilter, CommentFilter 
from .forms import AuditUpdateForm, AuditFunctionalForm
from django.core.exceptions import PermissionDenied
from django.contrib.auth import get_user_model

# used to redirect login on certain pages
from django.contrib.auth.mixins import LoginRequiredMixin

# admins see this page instead of the auditing page
class UserTripleView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/login/' 
    model = AuditTriple
    template_name = 'audit_user_triple_cards.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
       # original qs
       return super().get_queryset().filter().select_related('user','dataset')

    # add filter form
    def get_context_data(self, **kwargs):
        context = super(UserTripleView, self).get_context_data(**kwargs)
        context['filter'] = AuditUserTripleFilter(self.request.GET,queryset=self.get_queryset(),request=self.request)

        self.triple_filter = AuditUserTripleFilter(
            self.request.GET,
            queryset=AuditTriple.objects.all().select_related('user')
        )

        paginated_triple_filter = Paginator(self.triple_filter.qs,25)

        context = {'form': AuditFunctionalForm(request=self.request)}
        context['triple_filter'] = self.triple_filter 
        page_number = self.request.GET.get('page')
        page_obj = paginated_triple_filter.get_page(page_number)
        context['page_obj'] = page_obj

        return context

class UserTripleViewList(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/login/' 
    model = AuditTriple
    template_name = 'audit_user_triple_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
       # original qs
       return super().get_queryset().filter().select_related('user','dataset')

    # add filter form
    def get_context_data(self, **kwargs):
        context = super(UserTripleViewList, self).get_context_data(**kwargs)
        context['filter'] = AuditUserTripleFilter(self.request.GET,queryset=self.get_queryset(),request=self.request)

        self.triple_filter = AuditUserTripleFilter(
            self.request.GET,
            queryset=AuditTriple.objects.all().select_related('user')
        )

        paginated_triple_filter = Paginator(self.triple_filter.qs,25)

        context = {'form': AuditFunctionalForm(request=self.request)}
        context['triple_filter'] = self.triple_filter 
        page_number = self.request.GET.get('page')
        page_obj = paginated_triple_filter.get_page(page_number)
        context['page_obj'] = page_obj

        return context

class GroupsView(TemplateView):
    template_name = "audit_groups.html"

    def get_context_data(self):
        context = super(GroupsView,self).get_context_data()
        group_user_dict = {group.name: group.user_set.values_list('id', flat=True) for group in Group.objects.all()}
        simularity_dict = dict()

        a_set = set() 
        b_set = set() 

        for dataset in Dataset.objects.all():
            simularity_list = []
           # There are 2 users per group
            for group in group_user_dict:
                user1, user2 = group_user_dict[group]  
           
               # initial queries
                a = AuditTriple.objects.filter(user=user1,dataset=dataset).values_list('entityA','relation','entityB','verified')
                b = AuditTriple.objects.filter(user=user2,dataset=dataset).values_list('entityA','relation','entityB','verified')

                for trip in a:
                    a_set.add((trip[0],trip[1],trip[2],trip[3])) 

                for trip in b:
                    b_set.add((trip[0],trip[1],trip[2],trip[3])) 

                simularity_list.append(round(len(a_set&b_set)/len(a_set|b_set)*100,2))

                # clear set for next group
                a_set.clear()
                b_set.clear()

                simularity_dict[dataset] = simularity_list

            group_data = list(zip(group_user_dict.keys(),simularity_list))
            context['group_data'] = group_data
            context['simularity_dict'] = simularity_dict

        return context

def audit_triples(request):
    context = {}

    if not request.user.is_authenticated:
        raise PermissionDenied

    triple_filter = AuditTripleFilter(
        request.GET,
        queryset=AuditTriple.objects.filter(user=request.user).select_related('dataset')
    )

    paginated_triple_filter = Paginator(triple_filter.qs,50)
    context = {'form': AuditFunctionalForm(request=request)}
    context['triple_filter'] = triple_filter 
    page_number = request.GET.get('page')
    page_obj = paginated_triple_filter.get_page(page_number)
    context['page_obj'] = page_obj
    
    return render(request,'audit_triple_list.html',context=context)

def audit_triple_cards(request):
    context = {}

    if not request.user.is_authenticated:
        raise PermissionDenied

    triple_filter = AuditTripleFilter(
        request.GET,
        queryset=AuditTriple.objects.filter(user=request.user).select_related('dataset')
    )

    paginated_triple_filter = Paginator(triple_filter.qs,25)
    context = {'form': AuditFunctionalForm(request=request)}
    context['triple_filter'] = triple_filter 
    page_number = request.GET.get('page')
    page_obj = paginated_triple_filter.get_page(page_number)
    context['page_obj'] = page_obj
    
    return render(request,'audit_triple_cards.html',context=context)

class AuditTripleUpdate(LoginRequiredMixin,UpdateView):
    login_url = '/accounts/login/login/' 
    model = AuditTriple
    template_name = 'audit_triple_form.html' 
    form_class = AuditUpdateForm
  
    # if updated make verified False
    def form_valid(self,form):
        form.instance.verified = False
        return super().form_valid(form)

    # redirect back to the last page the auditor was on
    def get_success_url(self):
        return self.request.GET.get('next','/')

# Detail view for admins to view comments
class AuditTripleDetailView(DetailView):
    model = AuditTriple
    template_name = 'audit_triple_detail.html'

class ListDatasets(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/login/' 
    model = Dataset
    template_name = 'audit_list_datasets.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class DeleteDataset(LoginRequiredMixin, DeleteView):
    login_url = '/accounts/login/login/' 
    model = Dataset
    template_name = 'audit_dataset_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('Audit:audit_list_datasets')

class CommentView(LoginRequiredMixin, ListView):
    model = AuditTriple
    template_name = 'audit_comments.html'
    login_url = '/accounts/login/login/' 

    def get_queryset(self): 
        qs = super(CommentView, self).get_queryset()
        return qs.exclude(comment='').select_related('dataset','user').order_by('user')

    def get_context_data(self):
        context = super(CommentView, self).get_context_data()
        context['filter'] = CommentFilter(
            self.request.GET,
            queryset=self.get_queryset(),
            request=self.request
        )
        paginated_comment_filter = Paginator(context['filter'].qs,10)
        page_number = self.request.GET.get('page')
        page_obj = paginated_comment_filter.get_page(page_number)
        context['page_obj'] = page_obj
        return context

class GroupComparisons(LoginRequiredMixin, ListView):
    model = AuditTriple
    template_name = 'audit_comparisons.html'
    login_url = '/accounts/login/login/' 

    # Overwrite the queryset to return the unverified triples of the logged in user.
    def get_queryset(self):
        qs = super(GroupComparisons, self).get_queryset()
        return qs.filter(user=self.request.user,verified=False).select_related('user')

    def get_context_data(self):
        context = super(GroupComparisons, self).get_context_data()

        # users only have one group
        group = self.request.user.groups.all()[0]
         
        # get the name of the other group memeber
        other_group_member = get_user_model().objects.filter(
            groups__name=group).exclude(username=self.request.user.username) 
        
        # get search params for the other groups user
        entityA_list = self.get_queryset().values_list('entityA') 
        relation_list = self.get_queryset().values_list('relation') 
        entityB_list = self.get_queryset().values_list('entityB') 

        # only one other group member
        other_list = AuditTriple.objects.filter(
            user=other_group_member[0],
            entityA__in=entityA_list,
            relation__in=relation_list,
            entityB__in=entityB_list
        ).select_related('user','dataset') 

        context['other_list'] = other_list
        return context

Audit/templates/audit_list_datasets.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated%}
<p class="text-end">Logged in as {{ user.username }}</p>
{% else %}
 <p class="text-end">You are not logged in</p>
{%endif%}
<div class="container">
<h3>Delete Datasets</h3>
<h6>Deleting a dataset deletes it for everyone.</h6>
<table class="table table-striped table-hover" style="table-layout: fixed; word-wrap: break-word;">
  <thead>
    <tr>
      <th scope="col">#:</th>
      <th scope="col">Dataset:</th>
      <th scope="col">Delete:</th>
    </tr>
  </thead>
  <tbody>
      {% for dataset in object_list %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ dataset.name }}</td>
      <td><a href="{% url 'Audit:audit_delete_dataset' dataset.pk %}" class="btn btn-danger" role="button">Delete</a></td>
    </tr>
        
      {% endfor %}
  </tbody>
</div>
{% endblock content %}

Audit/templates/audit_triple_cards.html
<!--AuditTripleCards-->
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load audit_extras %}
{% block content %}
{% if user.is_authenticated%}
  <p class="text-end">Logged in as {{ user.username }}</p>
{% else %}
 <p class="text-end">You are not logged in</p>
{%endif%}
  <div class="container">
  <h1 class="text-center">Audit Triples</h1>
  <br/>
  <h5><a href={% url 'Audit:audit_triple_list' %}>Change to Table View</a></h5>
  <h6>Filter by a relation, entityA, entityB or any combination of the three.</h6>
  {% crispy form %} 
  <h6 class="text-end">Amount filtered: {{triple_filter.qs|length}}</h6>
  {% for object in page_obj %}
  {% if object.verified %}
  <h6>#{{ forloop.counter }}<h6>
  <div class="card border-success" style="width: 100%;">
    <h5 class="card-header">Dataset:  {{object.dataset}}</h5>
    <div class="card-body">
      <h4 class="card-text">EntityA:  {{object.entityA}}</h4>
      <h4 class="card-text">Relation:  {{object.relation}}</h4>
      <h4 class="card-text">EntityB:  {{object.entityB}}</h4>
      <h5 class="card-footer">Verified:  {{ object.verified }}</h5>
      <a href="{% url 'Audit:audit_triple_update' object.id %}?next={{request.get_full_path|urlencode}}" class="card-link btn btn-success">Comment</a>
  </div>
  {% else %}
  <div class="card border-danger" style="width: 100%;">
  <h5 class="card-header">Dataset:  {{object.dataset}}</h5>
  <div class="card-body">
    <h4 class="card-text">EntityA:  {{object.entityA}}</h4>
    <h4 class="card-text">Relation:  {{object.relation}}</h4>
    <h4 class="card-text">EntityB:  {{object.entityB}}</h4>
    <h5 class="card-footer">Verified:  {{ object.verified }}</h5>
    <h5 class="card-text"><b>Your Comment:</b>  {{object.comment}}</h5>
    <a  href="{% url 'Audit:audit_triple_update' object.id %}?next={{request.get_full_path|urlencode}}" class="card-link btn btn-success">Comment</a>
  </div>
  {% endif %}
</div>
<br/>
      {% endfor %}
  <div class="pagination">
    <span class="step-links">
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-primary btn-sm" href={% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}">Previous</a>
      <a class="btn btn-outline-primary btn-sm" href="{% my_url 1 'page' request.POST.urlencode %}">First</a>
    {% endif %}
      <span class="current">
        Page {{ page_obj.number}} of {{ page_obj.paginator.num_pages }}.
      </span>
     {% if page_obj.has_next %}
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">Last</a>
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">Next</a>
     {% endif %}
     </span>
  </div>
  <br/>
  </div>
{% endblock content %}

Audit/templates/audit_triple_list.html
<!--AuditTripleList-->
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load audit_extras %}
{% block content %}
{% if user.is_authenticated%}
  <p class="text-end">Logged in as {{ user.username }}</p>
{% else %}
 <p class="text-end">You are not logged in</p>
{%endif%}
  <h1 class="text-center">Audit Triples</h1>
  <br/>
  <h6>Filter by a relation, entityA, entityB or any combination of the three.</h6>
  {% crispy form %} 
  <h6 class="text-end">Amount filtered: {{triple_filter.qs|length}}</h6>
  <table class="table table-striped table-hover" style="table-layout: fixed; word-wrap: break-word;">
    <thead>
      <tr>
        <th scope="col" colspan="1">#</th>
        <th scope="col" colspan="1">Dataset:</th>
        <th scope="col" colspan="3">EntityA:</th>
        <th scope="col" colspan="3">Relation:</th>
        <th scope="col" colspan="3">EntityB:</th>
        <th scope="col" colspan="2">Verified:</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for object in page_obj %}
        <td colspan="1">{{ forloop.counter }}</td>
	<td colspan="1">{{ object.dataset }}</td>
        <td colspan="3">{{ object.entityA }}</td>
        <td colspan="3">{{ object.relation }}</td>
        <td colspan="3">{{ object.entityB }}</td>
        <td colspan="2">{{ object.verified }}</td>
	<td colspan="1"><a href="{% url 'Audit:audit_triple_update' object.id %}?next={{request.get_full_path|urlencode}}" class="btn btn-success" role="button">Update</td>
      </tr>
      {% endfor %}
        </form>
        </tbody>
  </table>
  <div class="pagination">
    <span class="step-links">
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-primary btn-sm" href={% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}">Previous</a>
      <a class="btn btn-outline-primary btn-sm" href="{% my_url 1 'page' request.POST.urlencode %}">First</a>
    {% endif %}
      <span class="current">
        Page {{ page_obj.number}} of {{ page_obj.paginator.num_pages }}.
      </span>
     {% if page_obj.has_next %}
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">Last</a>
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">Next</a>
     {% endif %}
     </span>
  </div>
  <br/>
{% endblock content %}

Audit/templates/audit_user_triple_cards.html
<!--AuditUserTripleCards-->
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load audit_extras %}
{% block content %}
{% if user.is_authenticated%}
  <p class="text-end">Logged in as {{ user.username }}</p>
{% else %}
 <p class="text-end">You are not logged in</p>
{%endif%}
<div class="container">
  <h1 class="text-center">User Triples</h1>
  <br/>
  <h5><a href={% url 'Audit:audit_user_triple_list' %}>Change to Table View</a></h5>
  <form method="GET">
  {% csrf_token %}
  {{ triple_filter.form | crispy }}
  <br/>
    <input style="inline-block" type="submit" class="btn btn-primary" value="Search"> 
  </form>

  <h6 class="text-end">Amount filtered: {{triple_filter.qs|length}}</h6>
  
{% for object in page_obj %}
  <h6>#{{ forloop.counter }}<h6>
  {% if object.verified %}
  <div class="card border-success" style="width: 100%;">
    <h5 class="card-header">Dataset:  {{object.dataset}}  |  User:  {{object.user}}</h5>
  <div class="card-body">
    <h4 class="card-text">EntityA:  {{object.entityA}}</h4>
    <h4 class="card-text">Relation:  {{object.relation}}</h4>
    <h4 class="card-text">EntityB:  {{object.entityB}}</h4>
    <h5 class="card-footer">Verified:  {{object.verified}}</h5>
    <p class="card-text"><b>Comment:</b>  {{object.comment}}</p>
  </div>
  {% else %}

  <div class="card border-danger" style="width: 100%;">
    <h5 class="card-header">Dataset:  {{object.dataset}}  |  User:  {{object.user}}</h5>
  <div class="card-body">
    <h4 class="card-text">EntityA:  {{object.entityA}}</h4>
    <h4 class="card-text">Relation:  {{object.relation}}</h4>
    <h4 class="card-text">EntityB:  {{object.entityB}}</h4>
    <h5 class="card-footer">Verified:  {{object.verified}}</h5>
    <p class="card-text"><b>Comment:</b>  {{object.comment}}</p>
  </div>

  {% endif %}
</div>
<br/>
{% endfor %}

  <div class="pagination">
    <span class="step-links">
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-primary btn-sm" href={% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}">Previous</a>
      <a class="btn btn-outline-primary btn-sm" href="{% my_url 1 'page' request.GET.urlencode %}">First</a>
    {% endif %}
      <span class="current">
        Page {{page_obj.number}} of {{ page_obj.paginator.num_pages }}.
      </span>

     {% if page_obj.has_next %}
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">Last</a>
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">Next</a>
     {% endif %}
     </span>
  </div>
  <br/>
  </div>
{% endblock content %}

Audit/templates/audit_user_triple_list.html
<!--AuditUserTripleList-->
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load audit_extras %}
{% block content %}
{% if user.is_authenticated%}
  <p class="text-end">Logged in as {{ user.username }}</p>
{% else %}
 <p class="text-end">You are not logged in</p>
{%endif%}
  <h1 class="text-center">User Triples</h1>
  <br/>
  <h5><a href={% url 'Audit:audit_user_triple_cards' %}>Change to Card View</a></h5>
  <form method="GET">
  {% csrf_token %}
  {{ triple_filter.form | crispy }}
  <br/>
    <input style="inline-block" type="submit" class="btn btn-primary" value="Search"> 
  </form>

  <h6 class="text-end">Amount filtered: {{triple_filter.qs|length}}</h6>
  <table class="table table-striped table-hover" style="table-layout: fixed; word-wrap: break-word;">
    <thead>
      <tr>
        <th scope="col" colspan="1">#</th>
        <th scope="col" colspan="1">Dataset:</th>
        <th scope="col" colspan="1">User:</th>
        <th scope="col" colspan="3">EntityA:</th>
        <th scope="col" colspan="3">Relation:</th>
        <th scope="col" colspan="3">EntityB:</th>
        <th scope="col" colspan="2">Verified:</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      {% for object in page_obj %}
        <td colspan="1">{{ forloop.counter }}</td>
        <td colspan="1">{{ object.dataset }}</td>
        <td colspan="1">{{ object.user }}</td>
        <td colspan="3">{{ object.entityA }}</td>
        <td colspan="3">{{ object.relation }}</td>
        <td colspan="3">{{ object.entityB }}</td>
        <td colspan="2">{{ object.verified }}</td>
	<td colspan="1"><a class="btn btn-success" href="{% url 'Audit:audit_triple_detail' object.id %}">View Comment</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="pagination">
    <span class="step-links">
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-primary btn-sm" href={% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}">Previous</a>
      <a class="btn btn-outline-primary btn-sm" href="{% my_url 1 'page' request.GET.urlencode %}">First</a>
    {% endif %}
      <span class="current">
        Page {{ page_obj.number}} of {{ page_obj.paginator.num_pages }}.
      </span>

     {% if page_obj.has_next %}
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">Last</a>
       <a class="btn btn-outline-primary btn-sm" href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">Next</a>
     {% endif %}
     </span>
  </div>
  <br/>
{% endblock content %}