Audit/urls.py
from django.urls import path
from . import views 

app_name = 'Audit'
urlpatterns = [

    # urls for everyone 
    path('Groups/', views.GroupsView.as_view(), name='audit_groups'),
    path('UserComments/',views.CommentView.as_view(), name='audit_comments'),
    path('GroupComparisons/',views.GroupComparisons.as_view(), name='audit_comparisons'),

    # urls for auditors
    path('AuditTripleList/', views.audit_triples, name='audit_triple_list'),
    path('AuditTripleCards/', views.audit_triple_cards, name='audit_triple_cards'),
    #path('AuditType/create/', AuditTypeCreate.as_view(), name='audit_type_create'),
    path('AuditTriple/<uuid:pk>/Update/', views.AuditTripleUpdate.as_view(), name='audit_triple_update'),

    # urls for admins
    path('UserTripleViewList/',views.UserTripleViewList.as_view(), name='audit_user_triple_list'),
    path('UserTripleViewCards/', views.UserTripleView.as_view(), name='audit_user_triple_cards'),
    path('<pk>/', views.AuditTripleDetailView.as_view(), name='audit_triple_detail'),

    path('delete/dataset/<pk>/', views.DeleteDataset.as_view(), name='audit_delete_dataset'),
    path('list/dataset/', views.ListDatasets.as_view(), name='audit_list_datasets'),

]

Entities/urls.py
from django.urls import path
from . import views

app_name = 'Entities'
urlpatterns = [
    path('Verified/', views.display_verified_entitys_view, name='display_verified'),
    path('Verified/<str:entity>/', views.display_verified_entitys_view, name='display_verified'),

    path('UnVerified/', views.display_unverified_entitys_view, name='display_unverified'),
    path('UnVerified/<path:entity>/', views.display_unverified_entitys_view, name='display_unverified'),
]

Relations/urls.py
from django.urls import path
from . import views

app_name = 'Relations'
urlpatterns = [
    path('Verified/', views.display_verified_relations_view, name='display_verified'),
    path('Verified/<str:relation>/', views.display_verified_relations_view, name='display_verified'),

    path('UnVerified/', views.display_unverified_relations_view, name='display_unverified'),
    path('UnVerified/<str:relation>/', views.display_unverified_relations_view, name='display_unverified'),
]

Types/urls.py
from django.urls import path
from . import views

app_name = 'Types'
urlpatterns = [
    path('Verified/', views.display_verified_types_view, name='display_verified'),
    path('Verified/<str:s_type>/', views.display_verified_types_view, name='display_verified'),

    path('UnVerified/', views.display_unverified_types_view, name='display_unverified'),
    path('UnVerified/<str:s_type>/', views.display_unverified_types_view, name='display_unverified'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

    # third party
    path('accounts/login/', include('allauth.urls')),

    # local
    path('', include('pages.urls')),
    path('UploadData/', include('UploadData.urls')),
    path('DisplayGraph/', include('DisplayGraph.urls')),
    path('Entities/', include('Entities.urls')),
    path('Types/', include('Types.urls')),
    path('Relations/', include('Relations.urls')),
    path('Charts/', include('Charts.urls')),
    path('Audit/', include('Audit.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Entities/views.py
from django.shortcuts import render
from UploadData import helper_methods as h
import networkx as nx

# Create your views here.

def display_verified_entitys_view(request,entity=None):

    context = dict()

    if "GET" == request.method:

        G = h.create_graph(request,'Verified')

        context['entities'] = sorted(list(G.nodes()))

        in_edges = G.in_edges(entity,data=True)
        out_edges = G.out_edges(entity,data=True)

        if entity != None:
            context['entity'] = entity
            context['types'] = h.get_entity_data(G,entity) 
            context['relation_set'] = set([v for k,v in nx.get_edge_attributes(G,'relation').items() if entity in k])

            context['draw_in_edges'] = h.get_image_planar(in_edges) 
            context['draw_out_edges'] = h.get_image_planar(out_edges) 

            out_edges_data = sorted([[trip[0],trip[2]['relation'],trip[1]] for trip in out_edges])
            
            out_edges_nums = [len(G.in_edges(ent[2],default=0)) + len(G.out_edges(ent[2],default=0)) for ent in out_edges_data]
            out_edges_percents = [round(edge/len(G.edges)*100,2) for edge in out_edges_nums]

            for i in range(len(out_edges_data)):
                out_edges_data[i].append(out_edges_nums[i])
                out_edges_data[i].append(out_edges_percents[i])
            

            in_edges_data = sorted([[trip[0],trip[2]['relation'],trip[1]] for trip in in_edges])

            in_edges_nums = [len(G.in_edges(ent[0],default=0)) + len(G.out_edges(ent[0],default=0)) for ent in in_edges_data]
            in_edges_percents = [round(edge/len(G.edges)*100,2) for edge in in_edges_nums]

            for i in range(len(in_edges_data)):
                in_edges_data[i].append(in_edges_nums[i])
                in_edges_data[i].append(in_edges_percents[i])

            context['out_edges_data'] = out_edges_data 
            context['in_edges_data'] = in_edges_data 

            context['unique_degree'] = len(in_edges) + len(out_edges)

            return render(request,'display_verified_entities.html',context)

        else:
            return render(request,'display_verified_entities.html',context)


def display_unverified_entitys_view(request,entity=None):

    context = dict()

    if "GET" == request.method:

        G = h.create_graph(request,'UnVerified')
        # remove None from user choice list
        entities = sorted(list(G.nodes()))

        context['entities'] = [ent for ent in entities if ent != 'None'] 

        in_edges = G.in_edges(entity,data=True)
        out_edges = G.out_edges(entity,data=True)

        if entity != None:
            context['entity'] = entity
            context['types'] = h.get_entity_data(G,entity) 
            context['relation_set'] = set([v for k,v in nx.get_edge_attributes(G,'relation').items() if entity in k])

            context['draw_in_edges'] = h.get_image_planar(in_edges) 
            context['draw_out_edges'] = h.get_image_planar(out_edges) 

            out_edges_data = sorted([[trip[0],trip[2]['relation'],trip[1]] for trip in out_edges])
            
            out_edges_nums = [len(G.in_edges(ent[2],default=0)) + len(G.out_edges(ent[2],default=0)) for ent in out_edges_data]
            out_edges_percents = [round(edge/len(G.edges)*100,2) for edge in out_edges_nums]

            for i in range(len(out_edges_data)):
                out_edges_data[i].append(out_edges_nums[i])
                out_edges_data[i].append(out_edges_percents[i])
            

            in_edges_data = sorted([[trip[0],trip[2]['relation'],trip[1]] for trip in in_edges])

            in_edges_nums = [len(G.in_edges(ent[0],default=0)) + len(G.out_edges(ent[0],default=0)) for ent in in_edges_data]
            in_edges_percents = [round(edge/len(G.edges)*100,2) for edge in in_edges_nums]

            for i in range(len(in_edges_data)):
                in_edges_data[i].append(in_edges_nums[i])
                in_edges_data[i].append(in_edges_percents[i])

            context['out_edges_data'] = out_edges_data 
            context['in_edges_data'] = in_edges_data 

            context['unique_degree'] = len(in_edges) + len(out_edges)

            return render(request,'display_unverified_entities.html',context)

        else:
            return render(request,'display_unverified_entities.html',context)

Entities/templates/display_unverified_entities.html
<!-- Entitys/display_unverified_entitys.html -->
{% extends '_base.html' %}
{% load static %}
{% block title %}Entities{% endblock title %}
{% block content %}
{% include 'unverified_graph_menu.html' %}

<form class="d-flex">
  <input class="form-control me-2" type="text" id="myInput" placeholder="Enter a entity" aria-label="Search">
  <button class="btn btn-outline-success" onClick="getEntityValue({{entities}});" id="myBtn" type="button">Search</button>
  </form>

  <div class="row">
    <div class="container col-3">
    <form>
      <label for="entitys">Entities:</label>
      <ul class="list-group">
        {% for ent in entities %}
	<li class="list-group-item list-group-item-secondary list-group-item-action text-break"><a href={% url 'Entities:display_unverified' ent %}>{{ent}}</a></li>
        {% endfor %}
      </ul>
  </form>
  </div>

  <div class="col-md-9">
    <h1 class="text-center">Combined Entites</h1>
<hr>
    <div class="row">
      <div class="col-6">
        <h3>Entities: {{ entity }}</h3>
      </div>
      <div class="col-6">
        <h3>Edges: {{ unique_degree }}</h3>
      </div>
    </div>

<hr>

   <div class="row">
     <div class="col-6">
       <h3 style=>Relations:</h3>
       {% for rel in relation_set %}
       <h5><a href="{% url 'Relations:display_unverified' rel %}" style="text-decoration:none;">{{ rel }}</a></h5>
       {% endfor %}
     </div>

   <div class="col-6">
     <h3>Semantic Types:</h3>
     {% for type in types %}
     <h5><a href="{% url 'Types:display_unverified' type %}" style="text-decoration:none;">{{ type }}</a></h5>
     {% endfor %}
   </div>
</div>

<hr>

  {% if draw_out_edges %}
      <h3>Connected To:</h3>
      <div class="offset-lg-2">
        {{ draw_out_edges | safe }}
    </div>
  {% endif %}

<hr>

     <table class="table table-striped table-hover">
      <thead>
        <tr>
        <th>EntityA:</th>
        <th>Relation</th>
        <th>EntityB</th>
        <th># of Edges</th>
        <th>% in Graph</th>
        </tr>
      </thead>
      <tbody>
        {% for data in out_edges_data %}
        <tr>
          <td>{{ data.0 }}</td>
	  <td><a href="{% url 'Relations:display_unverified' data.1 %}"style="text-decoration:none;">{{ data.1 }}</a></td>
	  <td><a href="{% url 'Entities:display_unverified' data.2 %}" style="text-decoration:none;">{{ data.2 }}</a></td>
	  <td>{{ data.3 }}</td>
	  <td>{{ data.4 }}</td>
        </tr>
	    {% endfor %}
      </tbody>
    </table>

<hr>

  {% if draw_in_edges %}
      <h3>Connected From:</h3>
      <div class="offset-lg-2">
      {{ draw_in_edges | safe }}
   </div>
{% endif %}

<hr>
     <table class="table table-striped able-hover">
      <thead>
        <tr>
        <th>EntityA:</th>
        <th># of Edges</th>
        <th>% in Graph</th>
        <th>Relation</th>
        <th>EntityB</th>
        </tr>
      </thead>
      <tbody>
	{% for data in in_edges_data %}
        <tr>
	  <td><a href="{% url 'Entities:display_unverified' data.0 %}" style="text-decoration:none;">{{ data.0 }}</a></td>
	  <td>{{ data.3 }}</td>
	  <td>{{ data.4 }}</td>
	  <td><a href="{% url 'Relations:display_unverified' data.1 %}" style="text-decoration:none;">{{ data.1 }}</a></td>
	  <td>{{ data.2 }}</td>
        </tr>
	{% endfor %}
      </tbody>
    </table>

  </div>
  <script src="{% static 'UploadData/search_unverified.js' %}"></script>

{% endblock content %}

Entities/templates/display_verified_entities.html
<!-- Entitys/display_verified_entitys.html -->
{% extends '_base.html' %}
{% load static %}
{% block title %}Entities{% endblock title %}
{% block content %}
{% include 'verified_graph_menu.html' %}

<form class="d-flex">
  <input class="form-control me-2" type="text" id="myInput" placeholder="Enter a entity" aria-label="Search">
  <button class="btn btn-outline-success" onClick="getEntityValue({{entities}});" id="myBtn" type="button">Search</button>
</form>

<div class="row">
  <div class="col-md-3">
    <form>
      <label for="entitys">Entities:</label>
      <ul class="list-group">
        {% for ent in entities%}
        <li class="list-group-item list-group-item-secondary list-group-item-action text-break"><a href={% url 'Entities:display_verified' ent %}>{{ent}}</a></li>
        {% endfor %}
      </ul>
    </form>
  </div>

  <div class="col-md-9 order-1">
    <h1 class="text-center">Official Entities</h1>
<hr>
    <div class="row">
      <div class="col-6">
        <h3>Entity: {{ entity }} </h3>
      </div>

      <div class="col-6">
        <h3>Edges: {{ unique_degree }}</h3>
      </div>
    </div>

<hr>
   <div class="row">
     <div class="col-6">
       <h3 style=>Relations:</h3>
       {% for rel in relation_set %}
       <h5><a href="{% url 'Relations:display_verified' rel %}" style="text-decoration:none;">{{ rel }}</a></h5>
       {% endfor %}
     </div>

   <div class="col-6">
     <h3>Semantic Types:</h3>
     {% for type in types %}
     <h5><a href="{% url 'Types:display_verified' type %}" style="text-decoration:none;">{{ type }}</a></h5>
     {% endfor %}
   </div>
 </div>

<hr>

  {% if draw_out_edges %}
      <h3>Connected To:</h3>
      <div class="offset-lg-2">
        {{ draw_out_edges | safe }}
      </div>
  {% endif %}

<hr>
     <table class="table table-striped table-hover">
      <thead>
        <tr>
        <th>EntityA:</th>
        <th>Relation</th>
        <th>EntityB</th>
        <th># of Edges</th>
        <th>% in Graph</th>
        </tr>
      </thead>
      <tbody>
        {% for data in out_edges_data %}
        <tr>
          <td>{{ data.0 }}</td>
	  <td><a href="{% url 'Relations:display_verified' data.1 %}"style="text-decoration:none;">{{ data.1 }}</a></td>
	  <td><a href="{% url 'Entities:display_verified' data.2 %}" style="text-decoration:none;">{{ data.2 }}</a></td>
	  <td>{{ data.3 }}</td>
	  <td>{{ data.4 }}</td>
        </tr>
	    {% endfor %}
      </tbody>
    </table>

<hr>

  {% if draw_in_edges %}
      <h3>Connected From:</h3>
      <div class="offset-lg-2">
      {{ draw_in_edges | safe }}
    </div>
{% endif %}

<hr>

     <table class="table table-striped able-hover">
      <thead>
        <tr>
        <th>EntityA:</th>
        <th># of Edges</th>
        <th>% in Graph</th>
        <th>Relation</th>
        <th>EntityB</th>
        </tr>
      </thead>
      <tbody>
	{% for data in in_edges_data %}
        <tr>
	  <td><a href="{% url 'Entities:display_verified' data.0 %}" style="text-decoration:none;">{{ data.0 }}</a></td>
	  <td>{{ data.3 }}</td>
	  <td>{{ data.4 }}</td>
	  <td><a href="{% url 'Relations:display_verified' data.1 %}" style="text-decoration:none;">{{ data.1 }}</a></td>
	  <td>{{ data.2 }}</td>
        </tr>
	{% endfor %}
      </tbody>
    </table>


  </div>
  </div>
  <script src="{% static 'UploadData/search_verified.js' %}"></script>

{% endblock content %}