Audit/urls.py
from django.urls import path
from . import views 

app_name = 'Audit'
urlpatterns = [

    # urls for everyone 
    path('Groups/', views.GroupsView.as_view(), name='audit_groups'),
    path('UserComments/',views.CommentView.as_view(), name='audit_comments'),
    path('GroupComparisons/',views.GroupComparisons.as_view(), name='audit_comparisons'),

    # urls for auditors
    path('AuditTripleList/', views.audit_triples, name='audit_triple_list'),
    path('AuditTripleCards/', views.audit_triple_cards, name='audit_triple_cards'),
    #path('AuditType/create/', AuditTypeCreate.as_view(), name='audit_type_create'),
    path('AuditTriple/<uuid:pk>/Update/', views.AuditTripleUpdate.as_view(), name='audit_triple_update'),

    # urls for admins
    path('UserTripleViewList/',views.UserTripleViewList.as_view(), name='audit_user_triple_list'),
    path('UserTripleViewCards/', views.UserTripleView.as_view(), name='audit_user_triple_cards'),
    path('<pk>/', views.AuditTripleDetailView.as_view(), name='audit_triple_detail'),

    path('delete/dataset/<pk>/', views.DeleteDataset.as_view(), name='audit_delete_dataset'),
    path('list/dataset/', views.ListDatasets.as_view(), name='audit_list_datasets'),

]

Charts/urls.py
from django.urls import path
from . import views

app_name = 'Charts'
urlpatterns = [
    path('degree/Verified', views.display_verified_degree_view, name='degree_verified'),
    path('relation/Verified', views.display_verified_relation_view, name='relation_verified'),
    path('out-relations/Verified', views.display_verified_out_relations_view, name='out_relations_verified'),

    path('degree/UnVerified', views.display_unverified_degree_view, name='degree_unverified'),
    path('relation/UnVerified', views.display_unverified_relation_view, name='relation_unverified'),
    path('out-relations/UnVerified', views.display_unverified_out_relations_view, name='out_relations_unverified'),
]

Entities/urls.py
from django.urls import path
from . import views

app_name = 'Entities'
urlpatterns = [
    path('Verified/', views.display_verified_entitys_view, name='display_verified'),
    path('Verified/<str:entity>/', views.display_verified_entitys_view, name='display_verified'),

    path('UnVerified/', views.display_unverified_entitys_view, name='display_unverified'),
    path('UnVerified/<path:entity>/', views.display_unverified_entitys_view, name='display_unverified'),
]

Types/urls.py
from django.urls import path
from . import views

app_name = 'Types'
urlpatterns = [
    path('Verified/', views.display_verified_types_view, name='display_verified'),
    path('Verified/<str:s_type>/', views.display_verified_types_view, name='display_verified'),

    path('UnVerified/', views.display_unverified_types_view, name='display_unverified'),
    path('UnVerified/<str:s_type>/', views.display_unverified_types_view, name='display_unverified'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

    # third party
    path('accounts/login/', include('allauth.urls')),

    # local
    path('', include('pages.urls')),
    path('UploadData/', include('UploadData.urls')),
    path('DisplayGraph/', include('DisplayGraph.urls')),
    path('Entities/', include('Entities.urls')),
    path('Types/', include('Types.urls')),
    path('Relations/', include('Relations.urls')),
    path('Charts/', include('Charts.urls')),
    path('Audit/', include('Audit.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path
from .views import HomePageView 

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

templates/_base.html
<!-- templates/_base.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Getting Bootstrap from cdn-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>{% block title %}{% endblock title %}</title><!-- JavaScript Bundle with Popper -->
    <style type="text/css">
      A:visited { COLOR: black; TEXT-DECORATION: none; font-weight: normal }
      A:link { COLOR: black; TEXT-DECORATION: none; font-weight: normal }
      A:hover { COLOR: blue; TEXT-DECORATION: none; font-weight: none }
    </style>
   </head>
  <body class="bg-light">
  <nav class="navbar navbar-dark navbar-expand-md bg-dark">
    <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>	
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:home' %}"style="color:white;text-decoration:none;">Home</a>
        </li>
	<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"style="color:white;text-decoration:none;">
           Explore Datasets
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
	    <li><a class="dropdown-item" href="{% url 'Entities:display_verified' %}">Verified</a></li>
            {% if user.is_authenticated %}
	    <li><a class="dropdown-item" href="{% url 'Entities:display_unverified'%}">Combined Dataset</a></li>
            {% endif %}
	    <!-- <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
          </ul>
          {% if user.is_staff %}
	  <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"style="color:white;text-decoration:none;">
           Audit Datasets
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
	    <li><a class="dropdown-item" href="{% url 'UploadData:upload' %}">Upload Datasets</a></li>
            {% if user.is_authenticated %}
	    <li><a class="dropdown-item" href="{% url 'Audit:audit_list_datasets'%}">Delete Datasets</a></li>
            {% endif %}
	    <!-- <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
          </ul>
        </li>
        {% endif %}
	{% if user.is_authenticated %}
	  <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"style="color:white;text-decoration:none;">
           Groups 
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
	    <li><a class="dropdown-item" href="{% url 'Audit:audit_groups' %}">Group Simularity</a></li>
	    {% if not user.is_staff %}
	      <li><a class="dropdown-item" href="{% url 'Audit:audit_comparisons' %}">Group Comparisons</a></li>
            {% endif %}
            {% if user.is_authenticated %}
	    <li><a class="dropdown-item" href="{% url 'Audit:audit_comments'%}">User Comments</a></li>
            {% endif %}
	    <!-- <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
          </ul>
        </li>
        {% endif %}
        </li>
        </li>
        {% if user.is_authenticated and not user.is_staff %}
        <li class="nav-item"><a class="nav-link" href="{% url 'Audit:audit_triple_cards' %}" role="button" style="color:white;text-decoration:none;">Audit Triples</a></li>
        {% endif %}
        {% if user.is_staff %}
        <li class="nav-item"><a class="nav-link" href="{% url 'Audit:audit_user_triple_cards' %}" role="button" style="color:white;text-decoration:none;">User Triples</a></li>
        {% endif %}
      </ul> 
     </div>
      <ul class="navbar-nav me-right mb-2 mb-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="btn btn-dark" href="{% url 'account_logout' %}" role="button" style="color:white;text-decoration:none;">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item px-2">
        <a class="btn btn-dark" href="{% url 'account_login' %}" role="button" style="color:white;text-decoration:none;">Log In</a>
        </li>
        <li class="nav-item px-2">
	<!--<a class="btn btn-dark" href="{% url 'account_signup' %}" role="button" style="color:white;text-decoration:none;">Sign Up</a>-->
        {% endif %}
        </li>
       </ul>
      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </nav>
  <div class="container-fluid">
    {% block content %}{% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>

templates/audit_menu.html
<!-- templates/audit_menu.html -->
<div class="row">
<div class="col-8">
<ul class="nav nav-pills">
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Audit:entity_list'%}" style="color:black;text-decoration:none;">Entities</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Audit:relation_list'%}" style="color:black;text-decoration:none;">Relations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Audit:type_list'%}" style="color:black;text-decoration:none;">Types</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Audit:triple_list'%}" style="color:black;text-decoration:none;">Triples</a>
  </li>
</ul>
</div>
<div class="col-4">{% if user.is_authenticated%}<p class="text-end">Logged in as {{ user.username }}</p>{%endif%}</div>
</div>

templates/home.html
<!-- templates/pages/home.html -->
{% extends '_base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
{% include 'verified_graph_menu.html' %}
<br>
<div class="container">
<div class="jumbotron">
    <h1 class="display-4">Welcome</h1>
    <p class="lead">This webapp is designed to help verify triple data.</p>
    <p class="lead">Users can explore verified data or the data to be audited by toggling between Datasets.</p>
    <p class="lead">To Audit data sign in.</p>
</div>
</div>
{% endblock content %}

templates/unverified_graph_menu.html
<div class="row">
<div class="col-8">
<ul class="nav nav-pills">
  <!-- <li class="nav-item">
    <a class="nav-link" aria-current="page" href="{% url 'UploadData:upload' %}">UploadData</a>
  </li> -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'DisplayGraph:display_unverified'%}" style="color:black;text-decoration:none;">GraphInfo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Entities:display_unverified'%}" style="color:black;text-decoration:none;">Entities</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Relations:display_unverified'%}" style="color:black;text-decoration:none;">Relations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Types:display_unverified'%}" style="color:black;text-decoration:none;">Types</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Charts:degree_unverified'%}" style="color:black;text-decoration:none;">Charts</a>
  </li>
</ul>
</div>
<div class="col-4">{% if user.is_authenticated%}<p class="text-end">Logged in as {{ user.username }}</p>{%endif%}</div>
</div>

templates/verified_graph_menu.html
<div class="row">
<div class="col-8">
<ul class="nav nav-pills" syle="display:inline;">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'DisplayGraph:display_verified'%}" style="color:black;text-decoration:none;">GraphInfo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Entities:display_verified'%}" style="color:black;text-decoration:none;">Entities</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Relations:display_verified'%}" style="color:black;text-decoration:none;">Relations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Types:display_verified'%}" style="color:black;text-decoration:none;">Types</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Charts:degree_verified'%}" style="color:black;text-decoration:none;">Charts</a>
  </li>
</ul>
</div>
<div class="col-4">{% if user.is_authenticated%}<p class="text-end">Logged in as {{ user.username }}</p>
{% else %}<p class="text-end">You are not logged in</p>
	{%endif%}</div>
</div>